title: Isaac Audet
description: Thoughts on AI and more
url: https://isaacaudet.com
baseurl: ""
author: Isaac Audet

# Social media
twitter_username: 
github_username: isaacaudet

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - serve.sh
  - serve.bat
  - new-post.sh
  - README.md
  - WRITING_GUIDE.md

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Isaac Audet"
      
# Theme settings
theme: jekyll-theme-primer 